name: skyrmion_unet_gpu
channels:
  - conda-forge
dependencies:
  - python==3.11
  - pip
  - pip:
      - notebook
      - numba
      - tensorflow[and-cuda]
      - albumentations
      - matplotlib
      - pandas
      - chardet
      - ipympl
      - ipywidgets
      - opencv-python-headless
      - wget
      - pyyaml
      - pillow